---
Name: FlexSlider
---
FlexSlider:
  db:
    SliderWidth: Int
    SliderHeight: Int
    Animation: Enum('slide, fade', 'slide')
    Loop: Boolean
    Animate: Boolean
    ThumbnailNav: Boolean
SlideImage:
  db:
    Name: Text
    Description: Text
    SortOrder: Int